FROM ghcr.io/bitwarden/self-host:beta
LABEL org.opencontainers.image.source=https://github.com/Jgigantino31/BitBetter

COPY ./temp/Api/Core.dll /app/Api/Core.dll
COPY ./temp/Identity/Core.dll /app/Identity/Core.dll
